// src/components/MusicGenres/WordCloud.tsx
import WordCloudInner from "react-d3-cloud";
import type { SpotifyArtists } from "../../types/spotify-artists";

const fillColor = "#3ABFF8";
const scalingFactor = 300;

export function WordCloud({ json }: { json: SpotifyArtists }) {
  const { items } = json;
  const genres: string[] = items.flatMap((i) => i.genres);
  const genreMap = genres.reduce(
    (acc: { [k: string]: number }, cur: string) => {
      if (acc?.[cur] !== undefined) {
        acc[cur] = acc[cur] + 1;
      } else {
        acc[cur] = 1;
      }
      return acc;
    },
    {},
  );
  const maxCount = Math.max(...Object.values(genreMap));
  const genreMapArray: { text: string; value: number }[] = Object.entries(
    genreMap,
  ).map(([text, value]) => ({
    text,
    value,
  }));
  return (
    <WordCloudInner
      fontSize={(word) => (word.value / maxCount) * scalingFactor}
      font={"Impact"}
      fill={fillColor}
      data={genreMapArray}
      padding={1}
      rotate={() => ~~(Math.random() * 2) * 90}
      spiral="archimedean"
    />
  );
}

// src/components/MusicGenres/WordCloud.svelte
<script lang="ts">
  import * as d3 from "d3";
  import cloud from "d3-cloud";
  import { onMount } from "svelte";

  export let genreMap: { [k: string]: number };

  // from daisyUI theme
  const fillColor = "#3ABFF8";
  const DIV_ID = "word-cloud";
  const scalingFactor = 300;
  const MIN_FONT_SIZE = 4;

  const words = Object.keys(genreMap);
  const maxCount = Math.max(...Object.values(genreMap));

  const layout = cloud()
    .size([960, 500])
    .words(
      words.map((d) => {
        const size = (genreMap[d] / maxCount) * scalingFactor;
        const adjustedSized = Math.max(MIN_FONT_SIZE, size);
        return {
          text: d,
          size: adjustedSized,
        };
      })
    )
    .padding(1)
    .rotate(function () {
      return ~~(Math.random() * 2) * 90;
    })
    .font("Impact")
    .fontSize(function (d) {
      return d.size;
    })

    .spiral("archimedean")
    .on("end", draw);

  function draw(words) {
    d3.select(`#${DIV_ID}`)
      .append("svg")
      .attr("width", layout.size()[0])
      .attr("height", layout.size()[1])
      .append("g")
      .attr(
        "transform",
        "translate(" + layout.size()[0] / 2 + "," + layout.size()[1] / 2 + ")"
      )
      .selectAll("text")
      .data(words)
      .enter()
      .append("text")
      .style("font-size", function (d) {
        return d.size + "px";
      })
      .style("font-family", "Impact")
      .attr("text-anchor", "middle")
      .attr("transform", function (d) {
        return "translate(" + [d.x, d.y] + ")rotate(" + d.rotate + ")";
      })
      .text(function (d) {
        return d.text;
      })
      .style("fill", fillColor);
  }

  onMount(() => {
    layout.start();
  });
</script>

<div class="content-center border-amber-800 border-solid">
  <div id={DIV_ID} />
</div>
